version: '3.0'

services:
    main:
        container_name: main
        build:
            context: .
        env_file:
            - .production.env
        volumes:
            - .:/dist
            - /dist/node_modules
        ports:
            - 5000:5000
            - 9229:9229
        command: npm run start
        depends_on:
            - postgres
        restart: always
    postgres:
        container_name: postgres
        image: postgres
        env_file:
            - .production.env
        environment:
            PG_DATA: /var/lib/postgresql/data
        ports:
            - 5432:5432
        volumes:
            - ./data:/var/lib/postgresql/data
            - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
        restart: always
